name: Check

on:
  pull_request:
  merge_group:

jobs:
  check:
    # if: ${{ github.event_name == 'merge_group' }}
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: "./.github/workflows/common.yml"
        with:
          ref: "master"
          path: "master"

      - name: Lint check
        run: yarn lint

      - name: Format check
        run: yarn prettier

      - name: Unit & Integration tests
        run: yarn test
