name: Check

on:
  pull_request:
  merge_group:

env:
  node_version: 18

jobs:
  check:
    # if: ${{ github.event_name == 'merge_group' }}
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: '[ -f .nvmrc ] && echo "node_version=$(cat .nvmrc)" >> $GITHUB_ENV'
      - name: "use node ${{ env.node_version  }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint check
        run: yarn lint

      - name: Format check
        run: yarn prettier

      - name: Unit & Integration tests
        run: yarn test
