name: "Update Pull Request"

on: pull_request

jobs:
  update_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: 'cul-\d+'
          title-template: "[%headbranch%] "
          body-template: |
            [Task V4 %headbranch%](https://notion.so/%headbranch%)
          body-update-action: "prefix"
